language: node_js
node_js: stable

# S: Build Lifecycle
install:
   - npm install



script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "sunxin"
  - git config user.email "xinsun92@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:hexo
  - hexo clean
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/sunsunstar/sunsunstar.github.io.git

#it failed, how is going?
